### ISSUE TITLE
Ignore qualifiers that are meaningless in a given context

### ISSUE THREAD

**Issue by zvr** [swhid/specification#31]
We have the fragment qualifiers `lines` and `bytes`.

I don't think they make sense for directory (`dir`) identifiers -- and I haven't thought about the rest of the types.

Shall we restrict them to only content (`cnt`) ones?

**Comment by rdicosmo** [comment]
Indeed, these qualifiers were introduced with only the `cnt` identifiers in mind, where it is very clear what their intended use is, so we could restrict them to only the `cnt` type.

From a purely technical point of view, though, they make sense for the other identifiers too: the specification describes how to build the byte sequence used to compute the hash of a `dir`, `rev`, `rel` or `snp`, and a qualifier may be used to point to a fragment of that sequence.

Hard for to say right now whether this will find an application in the near future.

Any thoughts?

**Comment by zvr** [comment]
Wow, thanks for this @zacchiro !

I was preparing a PR to add the "only for cnt" restriction to the fragment qualifiers, but it's much better to have a section on valid qualifiers according to object type.

**Comment by zacchiro** [comment]
> I was preparing a PR to add the "only for cnt" restriction to the fragment qualifiers, but it's much better to have a section on valid qualifiers according to object type.

I gave some thought about *where* to list the incompatibilities and there are at least two options:

1. have a single section putting all DONT'S together
2. in the section of each qualifier write where/when it should not be used (similar to what we already do for the lines qualifier, although in a currently suboptimal way)

(2) will induce some text repetition (about the SHOULD and the fact that implementations MUST ignore the "incorrect" qualifier), but it is currently my preference, because it is more likely that people checking the spec will notice the info there. (Very few people will explicitly look for a separate section about what not to do with something described elsewhere.)
