### ISSUE TITLE
Which variant of English is in use?

### ISSUE THREAD

**Issue by webmink** [swhid/specification#39]
I notice that the spellings [artefact ](https://github.com/search?q=repo%3Aswhid%2Fspecification+artefact&type=code) and [artifact](https://github.com/search?q=repo%3Aswhid%2Fspecification+artifact&type=code) are both used in the specification. The former is British English, the latter American English. Is the document adopting British or American English? Happy to fix :-)

**Comment by zacchiro** [comment]
Thanks for noticing!
We did not formally decide that early on in the process (and it shows ;-)), but generally speaking Software Heritage documentation, which is where the initial text of the SWHID specification came from, is in American English.
So it would be great to uniform in that direction, rather than the other.
Thanks in advance for the PR ;-)

**Comment by webmink** [comment]
Done.

**Comment by zacchiro** [comment]
Thanks! (will review those PRs separately)
