### ISSUE TITLE
Specify precisely the way the core identifier is computed for a directory node

### ISSUE THREAD

**Issue by rdicosmo** [swhid/specification#8]
We need a precise specification of the way one creates the textual document representing a directory node that is used as input to the sha1_git algorithm to obtain the hash used in a swh:1:dir: entry.

The relevant text in the document is the following:

https://github.com/swhid/specification/blob/642501a657a2f2f23f477c1280ffb7b83f47584e/Chapters/5_Core_identifiers.md?plain=1#L47-L72

**Comment by rdicosmo** [comment]
@zapashcanon this may be a place where your contribution will be very valuable

**Comment by zapashcanon** [comment]
IIRC, here's a [the relevant piece of code](https://github.com/OCamlPro/swhid_core/blob/main/src/compute.ml#L129-L138) in the OCaml implementation I wrote.

If you want to do a quick meeting one day where I explain the code and we write a textual version of the algorithm, I'm all for it. It's a good way to force me to take some time to do it. :-)

**Comment by zvr** [comment]
@zapashcanon I have no idea about OCaml, but looking at the code and @rdicosmo's description above, I can't help but wonder about details like:

- _decimal digits_ vs `%o`
- _the string `blob`_
- _ a space_ vs `\x00`

Details matter!

Even more interesting is the _name_ part -- no normalization of any kind?

**Comment by zapashcanon** [comment]
Yes, this code was not written after this particular spec, but it should be exactly what is implemented in software heritage. There's no test in the linked repository because it's a functorized implementation, but the functors are instantiated in another one (ocamlpro/swhid) where we did a lot of testing.

To answer your particular points:

- here `%o` is producing a sequence of six decimal digits (because I'm storing the permission as a regular int, that's just an implementation detail):

```ocaml
# Format.printf "%o" 33188;;
100644- : unit = ()
```

- the string `blob` is here, it's produced by [this call](https://github.com/OCamlPro/swhid_core/blob/main/src/compute.ml#L141)

- my guess is that `\x00` is part of the encoding of the name which is not yet described in the spec

I wrote this code two years ago so I don't remember everything...

**Comment by rdicosmo** [comment]
Thanks @zapashcanon , indeed, this is a good example of why we want to write a specification document :-)

**Comment by olasd** [comment]
With @rdicosmo and @zapashcanon we've updated the directory id specification to better match reality in #12.

@zvr I think the changes should address the inconsistencies that you've noticed.

**Comment by rdicosmo** [comment]
Closing after community review period for https://github.com/swhid/specification/pull/12
